# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

volumes:
  orderer2.example.com:
  peer0.r2s.example.com:
  peer0.r2f.example.com:
  peer0.b2.example.com:

networks:
  test:
    name: fabric_test

services:

  orderer.example2.com:
    container_name: orderer.example2.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7020
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example2.com:9447
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../custom/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations2/ordererOrganizations/example2.com/orderers/orderer.example2.com/msp:/var/hyperledger/orderer/msp
        - ../organizations2/ordererOrganizations/example2.com/orderers/orderer.example2.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example2.com:/var/hyperledger/production/orderer
    ports:
      - 7020:7050
      - 9447:9443
    networks:
      - test

  peer0.r2s.example.com:
    container_name: peer0.r2s.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.r2s.example.com
      - CORE_PEER_ADDRESS=peer0.r2s.example.com:7021
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7021
      - CORE_PEER_CHAINCODEADDRESS=peer0.r2s.example.com:7022
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7022
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.r2s.example.com:7021
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.r2s.example.com:7021
      - CORE_PEER_LOCALMSPID=R1SMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.r2s.example.com:9448
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations2/peerOrganizations/r2s.example.com/peers/peer0.r2s.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations2/peerOrganizations/r2s.example.com/peers/peer0.r2s.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.r2s.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7021:7021
      - 9448:9448
    networks:
      - test

  peer0.r2f.example.com:
    container_name: peer0.r2f.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.r2f.example.com
      - CORE_PEER_ADDRESS=peer0.r2f.example.com:9021
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9021
      - CORE_PEER_CHAINCODEADDRESS=peer0.r2f.example.com:9022
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9022
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.r2f.example.com:9021
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.r2f.example.com:9021
      - CORE_PEER_LOCALMSPID=R2FMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.r2f.example.com:9449
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations2/peerOrganizations/r2f.example.com/peers/peer0.r2f.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations2/peerOrganizations/r2f.example.com/peers/peer0.r2f.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.r2f.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9021:9021
      - 9449:9449
    networks:
      - test

  peer0.b2.example.com:
    container_name: peer0.b2.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.b2.example.com
      - CORE_PEER_ADDRESS=peer0.b2.example.com:11021
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11021
      - CORE_PEER_CHAINCODEADDRESS=peer0.b2.example.com:11022
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11022
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.b2.example.com:11021
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.b2.example.com:11021
      - CORE_PEER_LOCALMSPID=B2MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.b2.example.com:9450
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations2/peerOrganizations/b2.example.com/peers/peer0.b2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations2/peerOrganizations/b2.example.com/peers/peer0.b2.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.b2.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11021:11021
      - 9450:9450
    networks:
      - test

  # cli:
  #   container_name: cli
  #   image: hyperledger/fabric-tools:latest
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     # - FABRIC_LOGGING_SPEC=INFO
  #     - FABRIC_LOGGING_SPEC=DEBUG
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: /bin/bash
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
  #       - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
  #   depends_on:
  #     - peer0.r2s.example.com
  #     - peer0.r1f.example.com
  #     - peer0.b1.example.com
  #   networks:
  #     - test
